# Generated by Django 5.0 on 2023-12-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kategori', models.IntegerField()),
                ('nama_kategori', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'kategori',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_status', models.IntegerField()),
                ('nama_status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.AlterField(
            model_name='produk',
            name='id_produk',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produk',
            name='kategori_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produk',
            name='status_id',
            field=models.IntegerField(),
        ),
    ]
